apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentcar
  namespace: airbnb
  labels:
    app: rentcar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rentcar
  template:
    metadata:
      labels:
        app: rentcar
    spec:
      containers:
        - name: rentcar
          image: 879772956301.dkr.ecr.ap-northeast-1.amazonaws.com/user14-rentcar:1.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5